version: '3.8'

services:
  # =============================================================================
  # RabbitMQ with Host Networking for Cross-Node Access
  # =============================================================================
  
  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: cloudcam
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      # Use host mode for direct access from all nodes
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    networks:
      - camera-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    deploy:
      replicas: 1
      placement:
        constraints:
          # Must run on manager node for consistent IP address
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

# =============================================================================
# Networks
# =============================================================================
networks:
  camera-network:
    external: true

# =============================================================================  
# Volumes
# =============================================================================
volumes:
  rabbitmq_data:
    driver: local
